### ISSUE TITLE
bug

### ISSUE THREAD

**Issue by LiyingCheng95** [NJUNLP/GTS#3]

**Comment by LiyingCheng95** [comment]
Traceback (most recent call last):
  File "main.py", line 155, in <module>
    train(args)
  File "main.py", line 22, in train
    instances_train = load_data_instances(train_sentence_packs, args)
  File "/home/liying.cheng/GTS-main/code/BertModel/data.py", line 148, in load_data_instances
    tokenizer = BertTokenizer.from_pretrained(args.bert_tokenizer_path)
  File "/home/liying.cheng/anaconda3/lib/python3.7/site-packages/transformers/tokenization_utils_base.py", line 1796, in from_pretrained
    raise EnvironmentError(msg)
OSError: Can't load tokenizer for 'pretrained/bert-base-uncased/bert-base-uncased-vocab.txt'. Make sure that:

- 'pretrained/bert-base-uncased/bert-base-uncased-vocab.txt' is a correct model identifier listed on 'https://huggingface.co/models'

- or 'pretrained/bert-base-uncased/bert-base-uncased-vocab.txt' is the correct path to a directory containing relevant tokenizer files

**Comment by LiyingCheng95** [comment]
There's a bug: Traceback (most recent call last):
  File "main.py", line 155, in <module>
    train(args)
  File "main.py", line 22, in train
    instances_train = load_data_instances(train_sentence_packs, args)
  File "/home/liying.cheng/GTS-main/code/BertModel/data.py", line 148, in load_data_instances
    tokenizer = BertTokenizer.from_pretrained(args.bert_tokenizer_path)
  File "/home/liying.cheng/anaconda3/lib/python3.7/site-packages/transformers/tokenization_utils_base.py", line 1796, in from_pretrained
    raise EnvironmentError(msg)
OSError: Can't load tokenizer for 'pretrained/bert-base-uncased/bert-base-uncased-vocab.txt'. Make sure that:

- 'pretrained/bert-base-uncased/bert-base-uncased-vocab.txt' is a correct model identifier listed on 'https://huggingface.co/models'

- or 'pretrained/bert-base-uncased/bert-base-uncased-vocab.txt' is the correct path to a directory containing relevant tokenizer files

what should I change the args to?

**Comment by LiyingCheng95** [comment]
It works now. I fixed it.
